apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-shell-script
data:
  helm.sh: |
    #!/bin/sh

    set -e

    # $1 - Reliza Instance API Id
    # $2 - Reliza Instance API Key
    # $3 - Project Id of Helm Chart Project on Reliza Hub
    # $4 - Name/path of values file to use, relative to the base of the helm chart
    # $5 - Helm release name
    # $6 - Namespace to install release

    # 1. Obtain latest approved version of helm chart
    # 2. Download helm chart, extract required values file
    
    if [ "$#" -lt 6 ]
    then
      echo "Usage: reliza_instance_api_id reliza_instance_api_id helm_chart_project_id name_path_of_values_file helm_release_name namespace"
      exit 1
    fi
    
    mkdir -p work-values

    helm_chart_version=$(reliza-cli getlatestrelease -i $1 -k $2 --project $3 | jq -r ".version")
    helm_chart_identifier=$(reliza-cli getlatestrelease -i $1 -k $2 --project $3 | jq -r ".artifactDetails[0].identifier")
    helm_chart_name=$(echo $helm_chart_identifier | awk -F "/" '{print $NF}')
    helm_chart_uri=$(echo $helm_chart_identifier | awk -F "/$helm_chart_name" '{print $1}')

    helm repo add repo $helm_chart_uri
    helm repo update
    rm -rf $helm_chart_name/
    helm pull repo/$helm_chart_name --version $helm_chart_version --untar

    cp work-values/values.yaml work-values/values-prev.yaml || echo "no prev values file present yet" > work-values/values-prev.yaml
    reliza-cli replacetags -i $1 -k $2 --env TEST --infile $helm_chart_name/$4 --outfile work-values/values.yaml

    values_diff=$(diff work-values/values.yaml work-values/values-prev.yaml | wc -l)

    # check if release already deployed to figure out whether we do install or upgrade
    helm_command="upgrade"
    cur_releases=$(helm list -f "^$5$" -n $6 | wc -l)
    if [ $cur_releases -lt 2 ]
    then
      helm_command="install"
    fi
    echo $cur_releases
    echo $values_diff
    echo $helm_command

    if [ $values_diff -gt 0 ] || [ "install" == "$helm_command" ]
    then
      echo "Update required, performing..."
      helm $helm_command $5 -n $6 -f work-values/values.yaml repo/$helm_chart_name
    else
      echo "No diff in values, no upgrade will be performed"
    fi