apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: helm-reliza-sa
    app.kubernetes.io/part-of: helm-reliza
  name: helm-reliza-sa
  namespace: helmtests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helm-reliza-cr
  name: helm-reliza-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: helm-reliza-binding
    app.kubernetes.io/part-of: helm-reliza
  name: helm-reliza-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-reliza-cr
subjects:
- kind: ServiceAccount
  name: helm-reliza-sa
  namespace: helmtests
