FROM debian:stable-20200607-slim@sha256:92580848a13be1d3b04daad9644dde9b8f1756b0f9666e684fe4cd08a6f56d1d
RUN apt-get update
RUN apt-get --no-install-recommends -y install ca-certificates curl unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && /aws/install
RUN rm awscliv2.zip
ENTRYPOINT ["/usr/local/bin/aws"]